# Configuration Wrangler pour Cloudflare Pages
# Wrangler configuration for Cloudflare Pages

# Nom du projet / Project name
name = "ohmyai-app"

# Type de déploiement / Deployment type
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = ".svelte-kit/cloudflare"
